version: "3.8"
services:
    front-client:
        build:
            context: ./front-client
        image: front-client:latest
        ports:
            - 3000:3000
        networks:
            main2:
        hostname: "front-client.local"
        container_name: "front-client"
    front-admin:
        build:
            context: ./front-admin
        image: front-admin:latest
        ports:
            - 3001:3001
        networks:
            main2:
        hostname: "front-admin.local"
        container_name: "front-admin"
    server:
        depends_on:
            - db
        build:
            context: ./server
        image: server:latest
        ports:
            - 5000:5000
        networks:
            main2:
        hostname: "server.local"
        container_name: "server"
        command: "npm run start:dev"
    db:
        image: library/postgres:15
        hostname: "db.local"
        networks:
            main2:
        container_name: db
        env_file:
            - ./server/env/development.env
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4:latest
        env_file:
            - ./server/env/pgadmin.env
        ports:
            - 3002:80
        networks:
            main2:

networks:
    main2:
